# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce756d82ad99dd56f6d9b9b0d8b288416ba642db4096214e9ab6672bb9a176f1f7e1840f7f9e10403f9cf1f0ecdec6e532525b90bc841fb9fb26fe76123cafb9

test:
  secret_key_base: 0f664542f8193b6886369933de8ada5b771cb0d9f964bbc2835fc90bcf2594c5000c5e2f1f4db14f391c596b15a0feaac754c63c6f1725c3360bacfc43f71324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
